### ISSUE TITLE
原始数据能否共享下

### ISSUE THREAD

**Issue by PrivateThink** [howardhsu/DE-CNN#5]
您好，是否可以提供下原始数据呢，在文件data/official_data/的全部数据，谢谢您，我在整理下载数据的时候总是断。
data/official_data/Laptops_Test_Data_PhaseA.xml
data/official_data/Laptops_Test_Gold.xml
script/eval.jar
data/official_data/EN_REST_SB1_TEST.xml.A
data/official_data/EN_REST_SB1_TEST.xml.gold
script/A.jar

**Comment by howardhsu** [comment]
Sorry, we won't re-publish the original data.
