### ISSUE TITLE
F1 score replication

### ISSUE THREAD

**Issue by 19ravisha** [howardhsu/DE-CNN#9]
I have run the same code but could achieve the F1 score of 71.9 with the same hyperparameters, instead of 74.37 ( mentioned in the paper ). Can you please suggest what might have gone wrong? 
Thanks in advance!

**Comment by howardhsu** [comment]
I don't know what goes wrong but many factors may make that happen. 
I didn't get a 71.9 in my previous running.

Although I follow other paper to have 5 runs to be consistent, I feel the SemEval tends to have more running noises on 5 so I change the number of runs to 10 in my new [paper](https://github.com/howardhsu/BERT-for-RRC-ABSA). But 5 runs won't drop to 71.9 in my past experience.

**Comment by laugustyniak** [comment]
thx @howardhsu for publishing the source code! 

Unfortunately, I have the same problem as @19ravisha, I went through your instruction step-by-step, and I got F1:
- Laptops = 78.7% [**81.59%** is mentioned in paper]
- Restaurants = 71.4% [**74.37%** in paper]

If I see correctly, the master branch contains the best model and params as it is described in your paper. Do you have any idea why the F1 deteriorated so much?

**Comment by lacls** [comment]
I really appreciate your public code! But I couldn't follow your work well, and the point is at here:

 ```
   ./fastText/fasttext print-word-vectors data/embedding/restaurant_emb.vec.bin < data/prep_data/restaurant_emb.vec.oov.txt > data/prep_data/restaurant_oov.vec
    ^
SyntaxError: invalid syntax
```
So sorry for reopening this issue!

**Comment by gkonstanty** [comment]
Hi! I just want to let you know, that I also run the code according to step-by-step instruction and I got results similar to the ones described in your the paper:
  - laptop: 81.64%
  - restaurant: 74.29%

Here are some details about my environment:
- FastText 0.9.1
- I have run the computations on CPU (my GPU card is too old)
- looks like the sharing server with data from SemEval is currently down, so I have downloaded "official_data" from random GitHub repos - but I doubt that they differ from the original ones

**Comment by howardhsu** [comment]
glad to see you got similar numbers on CPU. (many factors can change my experiment setting and let all hyperparameters not valid any more)
